
from ast import Break
from time import sleep
#begin


while True:
    print("Het is een zaterdag ochtend je word wakker door een hard geluid en denkt woow wat is er aan de hand?")
    print("je loopt naar het raam en kijkt naar buiten en ziet kogels vliegen en un tank 3 blocken vederop")
    print("Je staat even stil na te denken wat je nu gaat doen?")
    sleep(2)
    print("Blijf ik om te helpen of vlucht ik?")
    print("A = Blijf")
    print("B = Vlucht")

    keusen1 = input ()
    if keusen1 == "B":
        print("Je vlucht naar het dichtbijzijnde verzamel punt voor un doorreis")
        sleep(5)
        print("Bij de boten lijkt het rustig we zouden via daar door kunnen vluchten")
        sleep(5)
        print("Of we pakken de vrachtwagen het lijkt niet op een goeie optie maar wel veilig en snel")
        sleep(5)
        print("Of lopen we door naar un buurland wat ongeveer 2 dagen gaat duren zonder eten of drinken")
        sleep(5)
        print("Wat gaan we doen?")
        print("A = Met de boot")
        print("B = Met de vrachtwagen")
        print("C = Lopen")
    

        Vlucht = input ()
        if Vlucht == "A":
            print("Het is geen grote boot maar je moet iets je zit met 40 andere op de boot en vertrekt net") 
            print("er Zitten veel kleine kinderen met hun ouders en 2 oudere mensen.. Je hoopt dat alles maar goed komt ")
            sleep(14)
            print("Je gaat maar slapen voor un paar uurtjes")
            sleep(5)
            print("Je word wakker door een plets water in je gezicht")
            sleep(5)
            print("het weer is zwaar verandert en de golven zijn super hoog")
            sleep(5)
            print("Je kan niks doen buiten jezelf vast houden aan de boot...")
            sleep(5)
            print("5 minuten later begint de boot omtezeilen..")
            sleep(5)
            print("je ziet iets om je aan vast te houden..")
            sleep(4)
            print("je ziet un ouder persoon probeeren we hem te helpen?")
            sleep(5)
            print("A = Nee")
            print("B = Ja")

            save = input ()

            if save == "A":
                print("Je gooit jezelf op de box en rust uit")
                sleep(5)
                print("Na zoon uur misslijk worden komt er un soort licht naar je toe...")
                sleep(8)
                print("Huh wacht wat un licht?!!")
                sleep(5)
                print("Het is un boot..")
                sleep(5)
                print("De boot helpt je aanboord er zitten nog 5 andere mensen..")
                sleep(4)
                print("Je bedenkt dat er zonet van de 40 mensen er maar 5 overleeft hebben")
                sleep(7)
                print("de boot brengt je naar de kust van nederland waar je veder word geholpen")
                sleep(8)
                print("Je schrijft je in en mag uiteindelijk blijven in nederland")
                sleep(5)
                print("Met de traumas die je allemaal op heb gelopen ga je naar therapie en word un uitkering aangeboden")
                print("A = Uitkering")
                print("B = Zoek werk")
                werk = input ()
                if werk == "A":
                    print("Je krijgt un uitkering en hebt un huis gerkegen van de regering de nieuwe buurd kijkt je raar aan omdat je nieuw bent en ze het nog niet allemaal begrijpen")
                    sleep(7)
                    print("Na un paar weken begin je je alleen te voelen wat niemand heeft nog contact met je proberen te maken")
                    print("A = probeer de taal te leren en contact te zoeken met je buuren")
                    print("B = Blijf thuis en probeer aan jezelf te werken")
                    contact = input ()
                    if contact == "A":
                        print("Je probeer de taal te leren het is lastig maar na un paar weken kan je jezelf voorstellen")
                        sleep(7)
                        print("je gaat naar je buren en stelt jezelf voor in gebrek nederlands en stukken engels kunnen jullie cominuseeren")
                        sleep(5)
                        print("Na un week weet bijna iedereen je verhaal en kijken ze je niet meer zo raar aan en bieden ze hulp aan")
                        sleep(5)
                        print("wat eerst voelde als een geen welkom gebied voelt nu als thuis..")
                        sleep(5)
                        print("________")
                        print("The settelment end")
                        sleep(40)
                        break
                    if contact == "B":
                        print("Na un week proberen aan jezelf te werken word je helemaal gek")
                        sleep(5)
                        print("er is niemand waar je contact mee hebt en je krijgt geen slaap meer door de nachtmerries")
                        sleep(6)
                        print("Je denkt na over het leven en denkt bij jezelf waarom ik waarom heb ik het overleefd...")
                        sleep(8)
                        print("je ziet geen nut meer in leven en eindigt het")
                        sleep(10)
                        print("_________")
                        print("Hoe heeft het zover kunnen komen.. einden")
                        sleep(40)
                        break
                if werk == "B":
                    print("Je bent opzoek naar un baan wat voor baan zouden we uberhoud willen??")
                    sleep(5)
                    print("A = Leer eerst de taal")
                    print("B = werk in een vabriek waar je geen taal kennis voor nodig hebt")
                    job = input ()
                    if job == "A":
                        print("Na 2 maanden heb je de taal un beetje onder de knie het was niet makkelijk maar met de doorsettings vermogen die je hebt heb je het kunnen doen")
                        sleep(8)
                        print("Je zoekt un baan in de zorg waar je ouden mensen helpt")
                        sleep(5)
                        print("uiteindelijk vraagt iemand hoe je hier bent gekomen en wat je verhaal is")
                        sleep(6)
                        print("Na een bakje koffie en een lang verhaal veder heb je je verhaal kunnen doen en bent blij want het voelt alsof er wat steenen van je rug af zijn gehaald")
                        sleep(7)
                        print("_______")
                        print("Mischien lijkt het niet zo maar mischien is dit de beste einde die er is")
                        sleep(50)
                        break

                    if job == "B":
                        print("Je komt in un nieuwe omgevig waar je met niemand kan praten en maar 10 uur werkt op un dag zodat je alles zelf kunt betallen")
                        sleep(8)
                        print("je denkt bij jezelf dat je het goeie hebt gekozen omdat er allemaal mensen werken dus waarom ik niet?")
                        sleep(8)
                        print("een aantal weeken gaan voorbij")
                        sleep(6)
                        print("uit je bed komen word lastig en denkt vaak over alles na wat er gebeurt is")
                        sleep(8)
                        print("Had ik dingen anders kunnen doen?")
                        sleep(6)
                        print("Na un jaar elke dag het zelfde weekende waar je niet je bed uitkomt besluit je dat je het niet meer trekt....")
                        sleep(8)
                        print("____________")
                        print("Depresie.... einde")
                        sleep(40)
                        break

            if save == "B":
                print("Je zwemt naar de oude man en pakt hem vast")
                sleep(5)
                print("je brengt hem naar de box waar je net jezelf aan vast hield")
                sleep(5)
                print("je zorgt dat hij er goed oplicht en dat hij kan rusten..")
                sleep(5)
                print("Je probeert zelf un ander houwvast punt te vinden zodat je zelf ook uitkanrusten")
                sleep(7)
                print("Je kan niks vinden en het zwemmen maakt je al snel moe..")
                sleep(5)
                print("_________")
                print("Drown end")
                sleep(50)
                break




        if Vlucht == "B":
            print("Je vraagt aan de schafeur of je achterin mag")
            sleep(4)
            print("Hij zegt dat het helemaal prima is als je maar stil bent als ze worden gecheckt en als je word gepakt hem er niet bij mag betrekken..")
            sleep(5)
            print("je stapt met 3 andere in de vrachtwagen en hij begint te rijden")
            sleep(6)
            print("na un goeie 3 uur klopt de schafeur op de achterkant van ze vrachtwagen jullie weten allemaal meteen dat het tijd is om te verstoppen")
            sleep(8)
            print("A = Achterin achter wat boxen")
            print("B = Voor in onder wat spullen")

            verstopt = input ()
            if verstopt == "A":
               print("Je gaat achet wat boxen zitten en spiekt nog even snel om het hoekje iemand gaat op de plek die je ander had gekozen zitten..")
               sleep(10)
               print("SSCHH")
               sleep(2)
               print("Owh ik hoop echt dat dit werkt..")
               sleep(5)
               print("Het lijkt stil te worden") 
               sleep(3)
               print("Je hoord un get geluid uit het niks..")
               sleep(5)
               print("Het is de guy die op jou andere plek ging zitten..")
               sleep(5)
               print("Owh shit hij word gewoon door geschoten waar hij ligt...")
               sleep(5)
               print("De schafeur begint gwn volgas te rijden zonder er teveel over na te denken kijk je of de andere okey zijn")
               sleep(10)
               print("Na zoon 3 uur hebben jullie het ook wel gehad")
               sleep(5)
               print("De vrachtwagen begint sloomer te rijden zouden we er zijn?")
               sleep(10)
               print("______")
               print("rij veilig.. Win")
               sleep(50)
               break

            if verstopt == "B":
                print("Nou daar gaan we dan onder wat houten planken en un kleed erboven laten we maar hopen dat dit goed gaat..")
                sleep(4)
                print("SSCHHH")
                sleep(2)
                print("Owh ik hoop echt dat dit werkt..")
                sleep(8)
                print("Het lijkt stil te worden..")
                sleep(4)
                print("WOOOSHHH")
                sleep(2)
                print("Owh shit..")
                sleep(5)
                print("__________")
                print("Niet de beste in verstoppen.. Einde")
                sleep(50)
                break
        if Vlucht == "C":
            print("Daar gaan we dan")
            sleep(10)
            print("Het begint al donker te worden")
            sleep(4)
            print("de schoten beginnen wel al minder hard te worden")
            sleep(4)
            print("We moeten wel ergens gaan schuilen")
            sleep(4)
            print("A = Blijf door lopen")
            print("B = Schuil onder wat boomen voor de nacht")

            slaap = input ()
            if slaap == "B":
                print("Je gaat lichen op de grond je bent bek af en valt binnen secondes inslaap")
                sleep(5)
                print("Het is zoon 4 uur veder het vriest buiten..")
                sleep(4)
                print("je lichaam trekt het niet meer en sluit af")
                sleep(4)
                print("__________")
                print("Koud Einde")
                sleep(50)
                break
            if slaap == "A":
                print("Je blijft doorlopen")
                sleep(4)
                print("Na 3 uren begin je toch wel wat koud te worden de vermoeheid gebrek van eten en drinken word je teveel")
                sleep(4)
                print("Je valt op de grond en kan begint rustig weg te vagen van de wereld")
                sleep(5)
                print("____________")
                print("Was lopen nou echt een goed idee? Einde")
                sleep(50)
                break



    if keusen1 == "A":
        print("Okey wat gaan we nu doen...")
        sleep(4)
        print("We gaan eerst naar buiten en dan kijken we wat we uberhoud kunnen doen")
        sleep(4)
        print("Okey ik denk dat het handig is als we eerst wat straaten veder lopen...")
        sleep(4)
        print("Owh god er liggen hier dode mensen...")
        sleep(4)
        print("mischien had ik toch maar moeten vluchten....")
        sleep(5)
        print("WOOW WAT IS DAT?!")
        sleep(4)
        print("er vloog zonet een raket over me heen in un gebouw...")
        sleep(4)
        print("Okey ik moet echt wat gaan doen ik kan hier niet blijven staan...")
        sleep(4)
        print("Wat gaan we doen pakken we un geweer van een dood persoon of gaan we kijken of er nog wat te redden valt bij het gebouw?")
        print("A = Pak un geweer")
        print("B = Ga naar het gebouw")
        keusen2 = input ()
        if keusen2 == "A":
            print("Okey dat was heel vies maar we hebben un geweer er zit nog un magezine in met un paar kogels gok ik..")
            sleep(4)
            print("Volgens mij zie ik daar slechte mensen die op andere schieten ik moet nu gaan helpen")
            sleep(4)
            print("Je rent er naar toe en begint te schieten")
            sleep(4)
            print("Piew Piew Piew")
            print("Piew")
            sleep(4)
            print("okey dat was geen goed idee ik heb nog nooit un geweer vast gepakt en hier lig ik dan op de grond met 3 kogels in me borst...")
            sleep(4)
            print("_____________")
            print("The idiot ending..")
            sleep(80)
            break
        if keusen2 == "B":
            print("Je rent naar het gebouw en hoord geschreeuw je twijvelt geen seconden en rent naar binnen")
            sleep(1)
            print("Je bent nu al 2 trappen omhoog gerent en voelt dat het lastiger word om te ademen ")
            sleep(1)
            print("Je hoord het geluid van een klein kind huilen en een moeder schreeuwen om hulp...")
            sleep(2)
            print("Je hebt ze gevonden en bekijkt de situatie en het ziet er niet goed uit de moeder schreeuwt 'Zorg dat me kind eerst in veiligheid is!!' wat gaan we doen?")
            print("A = Probeer de moeder en kind tegelijketijd te redden")
            print("B = Probeer het kind te redden")
            Brand = input ()
            if Brand == "A":
                print("je geeft het kind je shirt om voor ze mond te doen en gooit hem op je rug de moeder pak je stevig vast bij der arm en ze doet haar voor haar mond")
                sleep(1)
                print("het kind is redelijk zwaar maar op dit punt kan je het niks scheelen de lucht word lastiger om adem te halen je loopt met de trap naar beneden")
                sleep(3)
                print("Je bent bijna buien totdat er un balk voor de uitgang valt")
                sleep(1)
                print("Je haalt het kind van je rug af en slaat un raam door je gooit half het kind het raam uit en helpt de moeder daarna...")
                sleep(1)
                print("je bent de laatste die uit het gebouw is begint te hoesten van alle rook die in je longen is gekomen je bedenkt heb ik nou de goeie keuzen gemaakt??")
                sleep(4)
                print("je krijgt bijna geen adem meer en begint licht in je hoofd te worden voordat je het weet lig je op de grond geen bewust meer van wat er allemaal gebreurt...")
                sleep(5)
                print("je gaat dood door al het vuil in je longen..")
                print("_____________")
                print("De held... einde")
                sleep(80)
                break
            if Brand == "B":
                print("Het kind is het er niet mee eens en schreeuwt ze moeders naam terwijl je je shirt tegen ze mond houd zodat hij minder stoffen in ze lichaam komen je rent naar de uitgang")
                sleep(4)
                print("Je bent net naar buiten terwijl je je omdraait om terug naar binnen tegaan valt er een balk voor de ingang en je bekijkt goed de situatie er is geen manier hoe je de moeder nog kan redden je staat al te hoesen in pijn van de lucht die je binnen hebt gekregen")
                sleep(5)
                print("Ondanks het niet je kind is kan je het niet over je hard laten om hem hier alleen achter te laten dus je neemt hem mee en gaat opzoek naar een veilige plek")
                sleep(4)
                print("omdat je een klein kind mee hebt bied iemand aan om mee te gaan achterin een auto naar un buurland hier 3 uur vandaan je accepteert het aanbod en komt na 3 uur aan bij je buurland")
                sleep(6)
                print("Je krijgt daar un verblijf het is niet veel maar is iets na 2 jaar is de oorlog voorbij en kunnen jullie weer terug naar huis..")
                sleep(5)
                print("__________")
                print("Ik weet niet wat ik hier van moet vinden.. Win")
                sleep(50)
                break